AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template DynamoDB_Secondary_Indexes: Create
  a DynamoDB table with local and global secondary indexes. **WARNING** This template
  creates an Amazon DynamoDB table. You will be billed for the AWS resources used
  if you create a stack from this template.'
Outputs:
  TableName:
    Description: Name of the newly created DynamoDB table
    Value:
      Ref: TableOfBooks
Parameters:
  ReadCapacityUnits:
    ConstraintDescription: must be between 5 and 10000
    Default: '5'
    Description: Provisioned read throughput
    MaxValue: '10000'
    MinValue: '5'
    Type: Number
  WriteCapacityUnits:
    ConstraintDescription: must be between 5 and 10000
    Default: '10'
    Description: Provisioned write throughput
    MaxValue: '10000'
    MinValue: '5'
    Type: Number
Resources:
  TableOfBooks:
    Properties:
      AttributeDefinitions:
      - AttributeName: Title
        AttributeType: S
      - AttributeName: Category
        AttributeType: S
      - AttributeName: Language
        AttributeType: S
      GlobalSecondaryIndexes:
      - IndexName: TitleIndex
        KeySchema:
        - AttributeName: Title
          KeyType: HASH
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits:
            Ref: ReadCapacityUnits
          WriteCapacityUnits:
            Ref: WriteCapacityUnits
      KeySchema:
      - AttributeName: Category
        KeyType: HASH
      - AttributeName: Title
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: LanguageIndex
        KeySchema:
        - AttributeName: Category
          KeyType: HASH
        - AttributeName: Language
          KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits
    Type: AWS::DynamoDB::Table
