AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  IsMultiNodeCluster:
    Fn::Equals:
    - Ref: ClusterType
    - multi-node
Description: 'AWS CloudFormation Sample Template RedshiftClusterInVpc: Create an Amazon
  Redshift cluster in an Amazon Virtual Private Cloud (VPC). **WARNING** This template
  creates Amazon Redshift Cluster. You will be billed for the AWS resources used if
  you create a stack from this template.'
Outputs:
  ClusterEndpoint:
    Description: Endpoint for the newly created RedShift cluster
    Value:
      Fn::Join:
      - ':'
      - - Fn::GetAtt:
          - RedshiftCluster
          - Endpoint.Address
        - Fn::GetAtt:
          - RedshiftCluster
          - Endpoint.Port
Parameters:
  ClusterType:
    AllowedValues:
    - single-node
    - multi-node
    ConstraintDescription: must be single-node or multi-node.
    Default: single-node
    Description: The type of the cluster
    Type: String
  DatabaseName:
    AllowedPattern: ([a-z]|[0-9])+
    ConstraintDescription: must contain a-z or 0-9 only.
    Default: defaultdb
    Description: The name of the first database to be created when the redshift cluster
      is created
    Type: String
  DatabasePort:
    Default: '5439'
    Description: 'The port that Redshift will listen on and that will be allowed through
      the Security Group. '
    Type: String
  MasterUserPassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
    Description: 'The password associated with the master user account for the redshift
      cluster that is being created. '
    MaxLength: '41'
    MinLength: '1'
    NoEcho: 'true'
    Type: String
  MasterUsername:
    AllowedPattern: ([a-z])([a-z]|[0-9])*
    ConstraintDescription: must start with a-z and contain only a-z or 0-9.
    Description: The user name associated with the master user account for the redshift
      cluster that is being created
    NoEcho: 'true'
    Type: String
  NodeType:
    AllowedValues:
    - dw1.xlarge
    - dw1.8xlarge
    - dw2.large
    - dw2.8xlarge
    - dc1.large
    - dc1.8xlarge
    - ds1.xlarge
    - ds1.8xlarge
    - ds2.xlarge
    - ds2.8xlarge
    ConstraintDescription: must be a valid RedShift node type.
    Default: dc1.large
    Description: The node type to be provisioned for the redshift cluster
    Type: String
  NumberOfNodes:
    Default: '1'
    Description: 'The nuber of compute nodes in the redshift cluster.  When cluster
      type is specified as: 1) single-node, the NumberOfNodes parameter should be
      specified as 1, 2) multi-node, the NumberOfNodes parameter should be greater
      than 1'
    Type: Number
Resources:
  RedshiftCluster:
    Properties:
      ClusterParameterGroupName:
        Ref: RedshiftClusterParameterGroup
      ClusterSubnetGroupName:
        Ref: RedshiftClusterSubnetGroup
      ClusterType:
        Ref: ClusterType
      DBName:
        Ref: DatabaseName
      MasterUserPassword:
        Ref: MasterUserPassword
      MasterUsername:
        Ref: MasterUsername
      NodeType:
        Ref: NodeType
      NumberOfNodes:
        Fn::If:
        - IsMultiNodeCluster
        - Ref: NumberOfNodes
        - Ref: AWS::NoValue
      PubliclyAccessible: 'false'
      VpcSecurityGroupIds:
      - Ref: SecurityGroup
    Type: AWS::Redshift::Cluster
  RedshiftClusterParameterGroup:
    Properties:
      Description: Cluster paraeter group
      ParameterGroupFamily: redshift-1.0
      Parameters:
      - ParameterName: enable_user_activity_logging
        ParameterValue: 'true'
    Type: AWS::Redshift::ClusterParameterGroup
  RedshiftClusterSubnetGroup:
    Properties:
      Description: Cluster subnet group
      SubnetIds:
      - Ref: Subnet
    Type: AWS::Redshift::ClusterSubnetGroup
  SecurityGroup:
    Properties:
      GroupDescription: Security group
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/16
        FromPort:
          Ref: DatabasePort
        IpProtocol: tcp
        ToPort:
          Ref: DatabasePort
      VpcId:
        Ref: VPC
    Type: AWS::EC2::SecurityGroup
  Subnet:
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId:
        Ref: VPC
    Type: AWS::EC2::Subnet
  VPC:
    Properties:
      CidrBlock: 10.0.0.0/16
    Type: AWS::EC2::VPC
