AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template Route53_RoundRobin: Sample template
  showing how to use weighted round robin (WRR) DNS entried via Amazon Route 53. This
  contrived sample uses weighted CNAME records to illustrate that the weighting influences
  the return records. It assumes that you already have a Hosted Zone registered with
  Amazon Route 53. **WARNING** This template creates one or more AWS resources. You
  will be billed for the AWS resources used if you create a stack from this template.'
Outputs:
  DomainName:
    Description: Fully qualified domain name
    Value:
      Ref: MyDNSRecord
Parameters:
  HostedZone:
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    Type: String
Resources:
  MyDNSRecord:
    Properties:
      Comment: Contrived example to redirect to aws.amazon.com 75% of the time and
        www.amazon.com 25% of the time.
      HostedZoneName:
        Fn::Join:
        - ''
        - - Ref: HostedZone
          - .
      RecordSets:
      - Name:
          Fn::Join:
          - ''
          - - Ref: AWS::StackName
            - .
            - Ref: AWS::Region
            - .
            - Ref: HostedZone
            - .
        ResourceRecords:
        - aws.amazon.com
        SetIdentifier:
          Fn::Join:
          - ' '
          - - Ref: AWS::StackName
            - AWS
        TTL: '900'
        Type: CNAME
        Weight: '3'
      - Name:
          Fn::Join:
          - ''
          - - Ref: AWS::StackName
            - .
            - Ref: AWS::Region
            - .
            - Ref: HostedZone
            - .
        ResourceRecords:
        - www.amazon.com
        SetIdentifier:
          Fn::Join:
          - ' '
          - - Ref: AWS::StackName
            - Amazon
        TTL: '900'
        Type: CNAME
        Weight: '1'
    Type: AWS::Route53::RecordSetGroup
